### ISSUE TITLE
cl-patterns with alsa MIDI

### ISSUE THREAD

**Issue by turkja** [defaultxr/cl-patterns#1]
Hi! I'm interested in using cl-patterns for controlling MIDI, but cl-alsaseq has disappeared. Any idea what happened to it? Do you happen to have a copy of it?

**Comment by defaultxr** [comment]
Oh no! It looks like the original author deleted their repo. Fortunately I do have a copy saved. I've created the repo [here](https://github.com/defaultxr/cl-alsaseq). Let me know if you have any issues.
