### ISSUE TITLE
[Feature Request] Allow for :server-options key in start-backend

### ISSUE THREAD

**Issue by dylanjm** [defaultxr/cl-patterns#11]
I've been having to launch the sc server with a few options disabled using `sc-collider`.  So my `make-external-server` command has to be:

```lisp
(setf *s* (cl-collider::make-external-server
                        "localhost"
                        :port 8000
                        :server-options (cl-collider::make-server-options
                                         :num-input-bus 0
                                         :load-synthdefs-p 0)))
```

I've noticed there is no way to pass these options into `cl-patterns:start-backend`. Any way to make these args available through the `cl-patterns` interface?

**Comment by defaultxr** [comment]
Passing options to the backend via `start-backend` is a good idea, thanks. I've added it in commit e80c87b9fea750a4d4ce93dc2fd6acc3b215f41e ; any keyword arguments not recognized by `start-backend` will be passed to `make-server-options`. Let me know if you have any issues with it.

**Comment by dylanjm** [comment]
That looks great. Thank you!

**Comment by kflak** [comment]
Can you show an example of how this works? I'm trying with this, and I can't make the changes stick...

```common-lisp
(cl-patterns:backend-start 'supercollider 
                             :server-options (sc:make-server-options
                                              :num-input-bus 2
                                              :num-output-bus 2))
```

**Comment by defaultxr** [comment]
Oh cool, glad you got it working! Yes, the second snippet you posted should work; any keyword arguments not recognized by cl-patterns itself should be passed to cl-collider as server options when the server is being booted. So typing `sc:make-server-options` shouldn't be necessary.
