### ISSUE TITLE
Warning or error if something is `play`ed when the clock is stopped.

### ISSUE THREAD

**Issue by ntrocado** [defaultxr/cl-patterns#4]
This is still connected to the following post:

> No prob! Glad to hear it was something simple at least. Though it is strange that it would result in `nil`s if the clock wasn't running. Maybe it would be a good idea for me to implement some kind of warning or error if something is `play`ed when the clock is stopped.

_Originally posted by @defaultxr in https://github.com/defaultxr/cl-patterns/issues/3#issuecomment-478408260_

I forgot to create the clock and got the following error:
```
There is no applicable method for the generic function
  #<STANDARD-GENERIC-FUNCTION (SB-PCL::SLOT-ACCESSOR :GLOBAL
                               CL-PATTERNS::TASKS
                               SB-PCL::READER) (1)>
when called with arguments
  (NIL).
   [Condition of type SB-PCL::NO-APPLICABLE-METHOD-ERROR]
```
Maybe it's possible to have a more descriptive message that suggests the missing clock?

**Comment by defaultxr** [comment]
Sure thing, good idea. I've added a check for clock being `nil` in 741bbbc393b417b4c19c140c16cc687f4eaa086d . Let me know if you notice any other confusing/unhelpful error messages.
