### ISSUE TITLE
Can't build without xrandr

### ISSUE THREAD

**Issue by atgreen** [defaultxr/cl-patterns#41]
I maintain the ocicl package repo, which container cl-patterns.  cl-patterns stopped building in a headless environment (our build container image on github actions) ever since xrandr was required at load/build time to get the screen size.  It doesn't have to run.  I just want to make sure it builds before packaging it.

**Comment by defaultxr** [comment]
xrandr should only be called if the user attempts to use one of the functions involving screen size. These functions are run in the test suite which I believe is what is failing to build. The test suite is non-essential for normal use so its failure can be ignored. I intend to fix this fully when I am able, though; probably later today.

**Comment by atgreen** [comment]
I don't think this is test suite-related.  I'm just loading the system here:

https://github.com/ocicl/cl-patterns/actions/runs/6483931651/job/17606602736#step:2:811

**Comment by defaultxr** [comment]
Ah okay, yeah, now that I'm at my computer I see that you are correct. I think I've fixed the issue now, so the system should build as expected again. Thanks for reporting.
