### ISSUE TITLE
Reference to latest-output (should be last-output?) 

### ISSUE THREAD

**Issue by Yehouda** [defaultxr/cl-patterns#50]
https://github.com/defaultxr/cl-patterns/blame/b8ff9ae5e8db428802903b7ede4178168320bba7/src/backend.lisp#L255

This line has  a variable named **latest-output** that is not bound. There is also a variable **last-output** bound five lines earlier and not used. 
Is that just a typo?

I got a compiler warning, I didnt actually try to use this code.

**Comment by defaultxr** [comment]
Yup, you're right. Thanks for the heads up!
