### ISSUE TITLE
backend-stop supercollider not working

### ISSUE THREAD

**Issue by kflak** [defaultxr/cl-patterns#51]
Hi,

What the title says... If I run 
```common-lisp
(cl-patterns:backend-stop 'supercollider)
```
nothing happens. I need to run 
```common-lisp
(sc:server-quit sc:*s*)
``` 
to make the server quit.

Any help much appreciated!

**Comment by defaultxr** [comment]
I never manually shut down the server so I'm not surprised this slipped through the cracks. I think it should be fixed now though, let me know if not.

**Comment by kflak** [comment]
Works! Thanks for the quick fix :-)

**Comment by defaultxr** [comment]
No prob! Thank _you_ for helping me catch so many bugs :)

**Comment by kflak** [comment]
My pleasure 😊
