### ISSUE TITLE
The test clock depends on backend :debug to be enables.

### ISSUE THREAD

**Issue by Yehouda** [defaultxr/cl-patterns#8]
The test **clock** depends on the backend **:debug** to be enabled to work. The test **enable-debug-backend** enables **:debug**, but if **clock** runs without it or before it, it errors (it ends up calling **/=** with no arguments). 

Adding **(enable-backend :debug)** at the beginning of the test fixes it for me.

**Comment by defaultxr** [comment]
I've rewritten the test to use a fixture instead of enabling `:debug` in a separate test. I believe this should fix the issue. Thanks again.
